### ISSUE TITLE
Add support for 'resource' records

### ISSUE THREAD

**Issue by kathryn-gillespie** [AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin#14]
Some sites have minimally described collections or collections that do not have any inventory. In those cases, they'd like to be able to enable a request button at the 'resource' level so the collection can be requested. The option should be optional and sites can enable 'resource' level requesting, if desired.

**Comment by kathryn-gillespie** [comment]
Need an `aeon_resource_mapper.r` here: https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/tree/master/public/models

Also, probably need to add the word `resource` somewhere in this file: https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/blob/master/public/plugin_init.rb

**Comment by kathryn-gillespie** [comment]
I think it'd probably be best based on whether the resource has sub-records or not, but I can also see where a site might want to turn it off entirely. Though if we need to go one way or the other, I'd say the request option should be available at the resource level if no sub-records are present.

**Comment by AustinTSchaffer** [comment]
@kathryn-gillespie 
@stokesd 

I'm preparing to put in a pull request to add Resources as a supported type for the plugin. This PR will include adding support for resources, making user-defined fields and finding aid / EAD fields available to Aeon. Support for requesting resource records will be enabled by default. This PR would also add the changes described in Issue #8.

- If sites would like to disable resource requesting altogether, they will be able to use the `:aeon_fulfillment_record_types` configuration setting, which they can modify to include all record types except for 'resources'. The caveat here is that they would have to specify all of the other record types that they want to support, which will automatically exclude supported record types that are added in any future updates to this plugin, until they add that record type to the `:aeon_fulfillment_record_types` configuration setting.

- Alternatively, sites would be able to disable specific resource records based on their "Archival Record Level" property, where they can specify either (a) a white-list of all of the levels that they want to all patrons to request (such as "file", "item", "class") or (b) a black-list of all of the levels that they don't want to all patrons to request (such as "collection" or "series"). The caveat with this is that the setting would also apply to Archival Objects, and they would have to either assume or verify some consistency with their data. The advantage of this solution however, is that they would be able to exclude all Archival Objects that have sub-records, as long as their "level" properties are consistent.

Does this sound like a passable solution for now? If we want to add settings that apply specifically to resource records, that allow the toggling of support for resource records based on things like "this resource has subrecords, so we don't want people to be able to request it through this portal", we can add that as a separate backlog item and handle it as part of an additional pull request.

**Comment by tdilauro** [comment]
@AustinTSchaffer I think this could work for us at Johns Hopkins. We might need to make a few mapper changes, but that is not a problem for us.

I started to develop a resource mapper that meets our needs \[[here](https://github.com/tdilauro/ArchivesSpace-Aeon-Fulfillment-Plugin/commits/feature-resource_mapper)\] with the hope of integrating it into your code base, but happy that you are developing support. I note also that the set of fields that you're providing are more complete (more on that in another comment). 

Here are the features in which we are most interested:

1. Ability to submit requests on resource (among others) records;
2. Configurable option to limit availability of _resource-/collection_-level request button depending on presence of _instance_ with _top_container_ directly on that resource;
3. Configurable option to limit availability of _resource-/collection_-level request button depending on presence of child AOs.

The third is not yet implemented in my version of the plugin, but the other two are.

Looking forward to adopting your new functionality, once it is available.

**Comment by tdilauro** [comment]
Hi @AustinTSchaffer, I want to express concern about emitting the UDFs (especially the *string* and *text* ones) as part of the resource mapper functionality. More generally, I would be concerned about emitting any field that is at all likely to contain information that we do not wish to share with the public.

Because this plugin builds a form with data to post into Aeon, the content of these would be accessible (via *view page source* functionality, e.g.) to public users. While it would be possible to filter these out by modifying the *aeon/aeon_request_action* partial via an additional plugin, that might be too high a bar for some sites.

**Comment by AustinTSchaffer** [comment]
Hello @tdilauro,

**Inclusion of user defined fields**

Thanks for the point regarding the inclusion of UDFs. I will go ahead and pull those fields off of the PR now.

Some sites may want to include certain UDFs, so to avoid forcing sites to create a plugin for this plugin for those fields, would you like to see the inclusion of any UDFs as a configuration setting? We could add an `:allow_user_defined_fields` setting that accepts both (a) a true or false value, indicating that all UDFs should be grabbed/ignored, or (b) a list of the user defined fields that should be pulled from Accessions and Resources. We could also implement the setting similarly to the new `:requestable_archival_record_levels` setting, allowing sites to define either a whitelist or a blacklist of user defined fields. If this setting is something that you would be interested in, I'll put in an enhancement request into a different issue tab.

**Configurable option to limit availability of resource-/collection-level request button depending on presence of instance with top_container directly on that resource**

The `:requests_permitted_for_containers_only` setting will also apply to Resource records, so the requesting of resources can be limited to resources that have any Top Container instances. However, PR #25 does slightly modify the way that setting works, so we may need to add additional settings to control how that new functionality interacts with existing settings.

**Configurable option to limit availability of resource-/collection-level request button depending on presence of child AOs**

The attached PR also adds the functionality described on issue #8. The name for this setting will be `:requestable_archival_record_levels`. Do you believe that you would be able to use the new setting to accomplish that task? You would would have to check the consistency of your usage of the "Archival Record Level" enumeration, but you could presumably add `["collection"]` to that setting as a blacklist of levels, which could be used to disable requesting for all resources that have children. If that is not feasible, we can add create an additional enhancement request to add a setting to limit the requesting of resources based on the existence or absence of children.

**Comment by AustinTSchaffer** [comment]
@tdilauro We've completed a few pull requests that resolve the reason this enhancement was opened, but I'm leaving it so you have an opportunity to respond.

**Comment by tdilauro** [comment]
@AustinTSchaffer I think blacklist/whitelist would be a good way to handle availability of UDFs. The default behavior should be none (or at least none of the text/string ones).
