### ISSUE TITLE
Update script in ReadMe

### ISSUE THREAD

**Issue by kathryn-gillespie** [AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin#15]
The script in the ReadMe includes adding an entry to the OpenURLMapping table for ItemCallNumber, which is not a valid Aeon field. This line should be removed as that mapping will not do anything.

INSERT INTO OpenURLMapping (URL_Ver, rfr_id, AeonAction, AeonFieldName, OpenURLFieldValues, AeonValue) VALUES ('Default', 'ArchivesSpace', 'Replace', 'ItemCallNumber', '<#physical_location_note>', 'NULL');

**Comment by AustinTSchaffer** [comment]
Thanks @kathryn-gillespie
