### ISSUE TITLE
Add support for pulling location/instance information from parent objects, if the current object does not have that information

### ISSUE THREAD

**Issue by AustinTSchaffer** [AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin#9]
If there is no container or instance linked to the current Archival Object, the plugin should walk up the object's hierarchy within it's parent resource until it finds a record that has a container or instance and should pull the container info from there.

**Comment by kathryn-gillespie** [comment]
This should also be the case when an archival object is present with linked parent archival object, the information (series, sub-series, etc) should be able to be mapped from the higher levels.

The plugin is already bringing in Series, but should also bring in sub-series and any other level between Series and the Item. Example below of current series information, sub-series should be able to also bring in identifier and display string.

```

instance_top_container_series_identifier_1=1
instance_top_container_series_display_string_1=National+Educational+Television+Materials%2C+1955-1983

```

**Comment by stokesd** [comment]
Hey @kathryn-gillespie, what should happen if there is no parent with a container?  Should they still be able to request at that point? It sounds like this might need to be taken into consideration when we are determining whether the request button should be shown.

**Comment by AustinTSchaffer** [comment]
@stokesd I am working on this now. I am going to have the handling for this default to how it works currently, where no top container means no top container information is populated, in cases where requests are permitted for items that do not have an associated top container. I'll see if I can also incorporate the look-up-the-tree functionality into the `:requests_permitted_for_containers_only` setting, so requesting can be disabled if no top containers are found on any parent records.

**Comment by stokesd** [comment]
@AustinTSchaffer, that sounds great to me.  Institutions are already going to have to carefully consider each setting based on their own ArchivesSpace implementation and reading room rules (box requesting vs file requesting, etc).  Which option we use for a default likely isn't going to matter much as long as we have well documented what the setting does.
